- hosts: all
  remote_user: root
  vars:
     source_dir: /usr/local/weihu/software/centos6
     pkg: trc-jdk-1.8.0_77-1.el6.x86_64.rpm
  tasks:
     - name: check trc-jdk install or not
       shell: source /etc/profile;which java
       register: result
       ignore_errors: True
     - name: copy trc-jdk and install
       copy: src={{ source_dir }}/{{ pkg }} dest=/usr/local/weihu/
       #when: result|failed
       when: result is failed
       notify:
          - deploy trc-jdk
          - check
          - show check log
  handlers:
     - name: deploy trc-jdk
       shell:  rpm -ivh /usr/local/weihu/{{ pkg }}
     - name: check
       shell: source /etc/profile.d/java.sh;which java &>/dev/null && echo "install jdk successfully..." && exit 0 || echo "install jdk failure..." && exit 1
       register: check_result
     - name: show check log
       debug: var=check_result.stdout verbosity=0
