##替换客户端yum为本地yum源
- hosts: all
  vars:
    repo_dir: /yum/repo/local_repo
  tasks:
    - name: check /etc/yum.repos.d
      shell: ls -1 /etc/yum.repos.d | wc -l
      register: repo_file_num
    - name: backup repo files
      shell: rm -rf /etc/yum.repos.d.bak && mv /etc/yum.repos.d /etc/yum.repos.d.bak && mkdir /etc/yum.repos.d
      when: repo_file_num.stdout > 0
    - name: check os version
      shell: cat /etc/redhat-release | grep -o "[[:digit:]]" | head -1
      register: os_version
    - name: copy repo to remote(centos 6)
      copy: src={{ repo_dir }}/{{ item }} dest=/etc/yum.repos.d/
      with_items:
        - trc-centos6.repo
        - trc-epel6.repo
        - trc.repo
      when: os_version.stdout.find('6') != -1
      notify: 
        - add domain(repos.in.trc.com)
        - initial yum cache
    - name: copy repo to remote(centos 7)
      copy: src={{ repo_dir }}/{{ item }} dest=/etc/yum.repos.d/
      with_items:
        - trc-centos7.repo
        - trc-epel7.repo
        - trc.repo
      when: os_version.stdout.find('7') != -1
      notify:
        - add domain(repos.in.trc.com)
        - initial yum cache
  handlers:
    - name: add domain(repos.in.trc.com)
      shell: grep "repos.in.trc.com" /etc/hosts &>/dev/null ||  echo "10.211.202.13   repos.in.trc.com" >>/etc/hosts
    - name: initial yum cache
      shell: yum clean all && yum makecache && exit 0 || exit 1
