- hosts: all 
  remote_user: root
  vars:
      source_dir: /usr/local/weihu/other_software/zabbix-agent
      xs_agent_template: xs-zabbix_agentd.conf
      sq_agent_template: sq-zabbix_agentd.conf
      agent_checkscripts: check_scripts
  tasks:
      - name: install zabbix-agent
        yum: name="zabbix-agent" state=present
      - name: check hostname
        shell: hostname
        register: hostname_info
      - name: copy xs_agent_template to remote
        copy: src={{ source_dir }}/{{ xs_agent_template }} dest=/etc/zabbix/zabbix_agentd.conf
        when: hostname_info.stdout.find('-xs-') != -1
      - name: copy sq_agent_template to remote
        copy: src={{ source_dir }}/{{ sq_agent_template }} dest=/etc/zabbix/zabbix_agentd.conf
        when: hostname_info.stdout.find('-sq-') != -1
      - name: copy agent check_scripts to remote
        copy: src={{ source_dir }}/{{ agent_checkscripts }}/ dest=/etc/zabbix/{{ agent_checkscripts }}/
      - name: change privileges of {{ agent_checkscripts }}
        file: path=/etc/zabbix/{{ agent_checkscripts }} state=directory recurse=yes mode=0755
      - name: copy userparameter conf to remote
        copy: src={{ source_dir }}/zabbix_agentd.d/ dest=/etc/zabbix/zabbix_agentd.d/
        notify: 
            - check agent file
            - change privileges of /var/log/secure
            - start zabbix-agent
            - boot self starting zabbix-agent
            - check zabbix-agent status
            - show check agent file log
            - show zabbix-agent status log
  handlers:
      - name: check agent file
        shell: ls -1 /etc/zabbix/zabbix_agentd.conf && ls -1 /etc/zabbix/check_scripts && ls -1 /etc/zabbix/zabbix_agentd.d
        register: check_file_log
      - name: change privileges of /var/log/secure
        file: path=/var/log/secure owner=zabbix group=zabbix
      - name: start zabbix-agent
        shell: systemctl start zabbix-agent
      - name: boot self starting zabbix-agent
        shell: systemctl enable zabbix-agent 
      - name: check zabbix-agent status
        shell: systemctl status zabbix-agent | grep -i "active"
        register: agent_status_log
      - name: show check agent file log
        debug: var=check_file_log.stdout verbosity=0 
      - name: show zabbix-agent status log
        debug: var=agent_status_log.stdout verbosity=0
